#!/usr/bin/env .venv/bin/python
from kubeconf import BaseConfig, KubeconfSettings


@KubeconfSettings
class MyCustomConfig(BaseConfig):
    select_hint_text = "Select a configmap"
    size = "40%"
    show_preview = True
    preview_position = "right"
    preview_size = 50
